import type { Metadata } from "next";
import Link from "next/link";
import { MeaningReveal } from "@/components/learning/meaning-reveal";
import { SoundButton } from "@/components/learning/sound-button";
import { Container } from "@/components/ui/container";

export const metadata: Metadata = { title: "N5 Food, Places & Transportation Vocabulary" };
type Word = { kana: string; romaji: string; meaning: string; dictionaryForm?: string };
const groups: { label: string; title: string; description: string; words: Word[] }[] = [
  { label: "Food & Drinks", title: "အစားအသောက်နဲ့ သောက်စရာ", description: "စားသောက်ဆိုင်၊ အိမ်နဲ့ ဈေးဝယ်ရာမှာ မကြာခဏကြားရတဲ့ စကားလုံးများ", words: [
    { kana: "たべもの", romaji: "tabemono", meaning: "အစားအစာ" }, { kana: "のみもの", romaji: "nomimono", meaning: "သောက်စရာ" }, { kana: "パン", romaji: "pan", meaning: "ပေါင်မုန့်" }, { kana: "たまご", romaji: "tamago", meaning: "ကြက်ဥ / ဥ" }, { kana: "にく", romaji: "niku", meaning: "အသား" }, { kana: "さかな", romaji: "sakana", meaning: "ငါး" }, { kana: "やさい", romaji: "yasai", meaning: "ဟင်းသီးဟင်းရွက်" }, { kana: "くだもの", romaji: "kudamono", meaning: "သစ်သီး" }, { kana: "おちゃ", romaji: "ocha", meaning: "ဂျပန်လက်ဖက်ရည် / လက်ဖက်ရည်" }, { kana: "ぎゅうにゅう", romaji: "gyuunyuu", meaning: "နွားနို့" },
  ]},
  { label: "Places", title: "နေ့စဉ်သွားလာတဲ့ နေရာများ", description: "လမ်းမေးခြင်းနဲ့ ကိုယ်သွားမယ့်နေရာကို ပြောရာမှာ လိုအပ်တဲ့ စကားလုံးများ", words: [
    { kana: "がっこう", romaji: "gakkou", meaning: "ကျောင်း" }, { kana: "えき", romaji: "eki", meaning: "ဘူတာ" }, { kana: "びょういん", romaji: "byouin", meaning: "ဆေးရုံ" }, { kana: "ぎんこう", romaji: "ginkou", meaning: "ဘဏ်" }, { kana: "ゆうびんきょく", romaji: "yuubinkyoku", meaning: "စာတိုက်" }, { kana: "みせ", romaji: "mise", meaning: "ဆိုင်" }, { kana: "こうえん", romaji: "kouen", meaning: "ပန်းခြံ" }, { kana: "としょかん", romaji: "toshokan", meaning: "စာကြည့်တိုက်" }, { kana: "うち", romaji: "uchi", meaning: "အိမ် / ကိုယ့်အိမ်" }, { kana: "くに", romaji: "kuni", meaning: "နိုင်ငံ / ကိုယ့်နိုင်ငံ" },
  ]},
  { label: "Transportation · ます Form", title: "သယ်ယူပို့ဆောင်ရေးနဲ့ လှုပ်ရှားမှု", description: "ယာဉ်အမျိုးအစားတွေနဲ့ ခရီးသွားရာမှာသုံးတဲ့ အခြေခံ ます-form ကြိယာများ", words: [
    { kana: "でんしゃ", romaji: "densha", meaning: "ရထား" }, { kana: "バス", romaji: "basu", meaning: "ဘတ်စ်ကား" }, { kana: "じてんしゃ", romaji: "jitensha", meaning: "စက်ဘီး" }, { kana: "ひこうき", romaji: "hikouki", meaning: "လေယာဉ်" }, { kana: "ふね", romaji: "fune", meaning: "သင်္ဘော / လှေ" }, { kana: "タクシー", romaji: "takushii", meaning: "တက္ကစီ" }, { kana: "あるきます", romaji: "arukimasu", dictionaryForm: "あるく · aruku", meaning: "လမ်းလျှောက်သည်" }, { kana: "のります", romaji: "norimasu", dictionaryForm: "のる · noru", meaning: "ယာဉ်ပေါ်တက်သည် / စီးသည်" }, { kana: "おります", romaji: "orimasu", dictionaryForm: "おりる · oriru", meaning: "ယာဉ်ပေါ်မှ ဆင်းသည်" }, { kana: "つきます", romaji: "tsukimasu", dictionaryForm: "つく · tsuku", meaning: "ရောက်ရှိသည်" },
  ]},
];
function WordCard({ word, number }: { word: Word; number: number }) { return <article className="rounded-[1.5rem] border border-[#ded8ca] bg-[#fffdf8] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black tracking-[.16em] text-[#8a8276]">WORD {String(number).padStart(2, "0")}</p><p lang="ja" className="mt-2 text-3xl font-black text-[#a33a32]">{word.kana}</p><p className="mt-1 text-xs font-bold text-[#746c60]">{word.romaji}</p>{word.dictionaryForm && <p className="mt-3 text-[11px] text-[#8a8276]"><span className="font-black text-[#31513e]">မူရင်းပုံစံ</span> · <span lang="ja">{word.dictionaryForm}</span></p>}</div><SoundButton audioUrl={`/audio/n5/vocabulary/food-places-transport/${word.romaji}.mp3`} label={word.kana} /></div><MeaningReveal meaning={word.meaning} /></article>; }
export default function Page() { return <div className="washi-surface min-h-screen bg-[#f7f5ef] text-[#172033]"><header className="border-b border-[#ded8ca] bg-[#fffdf8]"><Container className="py-7"><Link href="/learn/n5/vocabulary" className="text-xs font-bold text-[#746c60]">← Vocabulary Topics</Link><p className="mt-6 text-xs font-black tracking-[.2em] text-[#a33a32] uppercase">Lesson 05 · たべもの・ばしょ</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Food, Places & Transport</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-[#746c60]">စားသောက်ခြင်းနဲ့ နေ့စဉ်သွားလာရာမှာ လိုအပ်တဲ့ N5 စကားလုံး ၃၀ ကို Hiragana၊ Katakana၊ Romaji နဲ့ အသံတွဲပြီး လေ့လာမယ်။ Kanji ကို မထည့်သေးပါဘူး။</p></Container></header><Container className="py-10 sm:py-14">{groups.map((group, groupIndex) => <section key={group.label} className={groupIndex ? "mt-14" : ""}><p className="text-xs font-black tracking-[.18em] text-[#a33a32] uppercase">{group.label}</p><h2 className="mt-2 text-2xl font-black">{group.title}</h2><p className="mt-2 text-sm text-[#746c60]">{group.description}</p><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{group.words.map((word, wordIndex) => <WordCard key={word.romaji} word={word} number={groupIndex * 10 + wordIndex + 1} />)}</div></section>)}<div className="mt-12 flex flex-wrap justify-between gap-3"><Link href="/learn/n5/vocabulary/daily-life" className="rounded-xl border border-[#cfc6b7] bg-white px-5 py-3 text-sm font-bold">← Previous Lesson</Link><Link href="/learn/n5/vocabulary/adjectives-questions-greetings" className="rounded-xl bg-[#d43d34] px-5 py-3 text-sm font-black text-white transition hover:bg-[#b92f28]">Next Lesson →</Link></div></Container></div>; }
