import type { Metadata } from "next";
import Link from "next/link";
import { MeaningReveal } from "@/components/learning/meaning-reveal";
import { SoundButton } from "@/components/learning/sound-button";
import { Container } from "@/components/ui/container";

export const metadata: Metadata = { title: "Japanese Time & Hours" };
const hours = [
  ["1:00","いちじ","ichiji","၁ နာရီ"],["2:00","にじ","niji","၂ နာရီ"],["3:00","さんじ","sanji","၃ နာရီ"],["4:00","よじ","yoji","၄ နာရီ","special"],["5:00","ごじ","goji","၅ နာရီ"],["6:00","ろくじ","rokuji","၆ နာရီ"],["7:00","しちじ","shichiji","၇ နာရီ","special"],["8:00","はちじ","hachiji","၈ နာရီ"],["9:00","くじ","kuji","၉ နာရီ","special"],["10:00","じゅうじ","juuji","၁၀ နာရီ"],["11:00","じゅういちじ","juuichiji","၁၁ နာရီ"],["12:00","じゅうにじ","juuniji","၁၂ နာရီ"],
];
const words = [
  ["いま","ima","အခု","いま、さんじです。","အခု ၃ နာရီပါ။"],["ごぜん","gozen","မနက်ပိုင်း / AM","ごぜん しちじ","မနက် ၇ နာရီ"],["ごご","gogo","မွန်းလွဲပိုင်း / PM","ごご さんじ","မွန်းလွဲ ၃ နာရီ"],["はん","han","နာရီဝက် / နာရီခွဲ","くじ はん","၉ နာရီခွဲ"],["なんじ","nanji","ဘယ်နှနာရီ","いま、なんじですか。","အခု ဘယ်နှနာရီလဲ။"],["じかん","jikan","ကြာချိန် / နာရီ","にじかん","နှစ်နာရီကြာ"],
];

export default function Page() {
  return <div className="washi-surface min-h-screen bg-[#f7f5ef] text-[#172033]"><header className="border-b border-[#ded8ca] bg-[#fffdf8]"><Container className="py-7"><Link href="/learn/n5/vocabulary" className="text-xs font-bold text-[#746c60]">← Vocabulary Topics</Link><p className="mt-6 text-xs font-black tracking-[.2em] text-[#a33a32] uppercase">Lesson 02 · Time</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Time & Hours</h1><p className="mt-3 text-sm text-[#746c60]">Hiragana အသံထွက်နဲ့ မြန်မာအဓိပ္ပာယ်ကို တွဲမှတ်ပါ။ 4၊ 7၊ 9 နာရီဖတ်ပုံက အထူးဖြစ်ပါတယ်။</p></Container></header><Container className="py-10 sm:py-14"><section><h2 className="text-2xl font-black">နာရီအချိန် ဖတ်ပုံ</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{hours.map(([clock,reading,key,meaning,special]) => <article key={key} className={`rounded-[1.5rem] border bg-[#fffdf8] p-5 ${special ? "border-[#d8766e]" : "border-[#ded8ca]"}`}><div className="flex justify-between"><p className="text-lg font-black text-[#625b50]">{clock}</p><SoundButton audioUrl={`/audio/n5/vocabulary/time/${key}.mp3`} label={reading} /></div><p lang="ja" className="mt-4 text-2xl font-black text-[#a33a32]">{reading}</p><p className="mt-1 text-xs text-[#8a8276]">{key}</p><MeaningReveal meaning={meaning} />{special && <p className="mt-2 text-[10px] font-black text-[#a33a32]">★ အထူးဖတ်ပုံ</p>}</article>)}</div></section><section className="mt-14"><h2 className="text-2xl font-black">လက်တွေ့သုံး အချိန်စကားလုံးများ</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{words.map(([reading,key,meaning,example,translation]) => <article key={key} className="rounded-[1.5rem] border border-[#ded8ca] bg-[#fffdf8] p-5"><div className="flex justify-between"><div><p lang="ja" className="text-3xl font-black text-[#a33a32]">{reading}</p><p className="mt-1 text-xs text-[#8a8276]">{key}</p></div><SoundButton audioUrl={`/audio/n5/vocabulary/time/${key}.mp3`} label={reading} /></div><div className="mt-4 rounded-xl bg-[#f3efe6] p-4"><p lang="ja" className="font-bold">{example}</p></div><MeaningReveal meaning={meaning} detail={translation} /></article>)}</div></section><div className="mt-10 flex justify-between gap-3"><Link href="/learn/n5/vocabulary/numbers-1-10" className="rounded-xl border border-[#cfc6b7] bg-white px-5 py-3 text-sm font-bold">← Previous Lesson</Link><Link href="/learn/n5/vocabulary/days-dates-months" className="rounded-xl bg-[#c83f35] px-5 py-3 text-sm font-black text-white">Next Lesson →</Link></div></Container></div>;
}
