import type { Metadata } from "next";
import Link from "next/link";
import { MeaningReveal } from "@/components/learning/meaning-reveal";
import { SoundButton } from "@/components/learning/sound-button";
import { Container } from "@/components/ui/container";

export const metadata: Metadata = { title: "N5 Adjectives, Questions & Greetings" };
type Word = { kana: string; romaji: string; meaning: string; note?: string };
const groups: { label: string; title: string; description: string; words: Word[] }[] = [
  { label: "Common Adjectives", title: "အသုံးများတဲ့ ဖော်ပြစကားလုံး", description: "လူ၊ ပစ္စည်း၊ ရာသီဥတုနဲ့ ဈေးနှုန်းကို ရိုးရိုးရှင်းရှင်း ဖော်ပြဖို့သုံးတဲ့ စကားလုံးများ", words: [
    { kana: "おおきい", romaji: "ookii", meaning: "ကြီးသော" }, { kana: "ちいさい", romaji: "chiisai", meaning: "သေးငယ်သော" }, { kana: "あたらしい", romaji: "atarashii", meaning: "အသစ်ဖြစ်သော" }, { kana: "ふるい", romaji: "furui", meaning: "ဟောင်းသော", note: "လူရဲ့ အသက်ကြီးမှုကို ပြောရာမှာ မသုံးပါဘူး။" }, { kana: "いい", romaji: "ii", meaning: "ကောင်းသော" }, { kana: "わるい", romaji: "warui", meaning: "မကောင်းသော" }, { kana: "あつい", romaji: "atsui", meaning: "ပူသော" }, { kana: "さむい", romaji: "samui", meaning: "အေးသော (ရာသီဥတု)" }, { kana: "たかい", romaji: "takai", meaning: "ဈေးကြီးသော / မြင့်သော" }, { kana: "やすい", romaji: "yasui", meaning: "ဈေးသက်သာသော" },
  ]},
  { label: "Question Words", title: "မေးခွန်းမေးရာမှာ သုံးတဲ့စကားလုံး", description: "N5 စာကြောင်းတည်ဆောက်ရာမှာ မရှိမဖြစ်လိုအပ်တဲ့ ဘယ်သူ၊ ဘယ်မှာ၊ ဘယ်အချိန် စတဲ့ မေးခွန်းစကားလုံးများ", words: [
    { kana: "なに・なん", romaji: "nani / nan", meaning: "ဘာ / ဘာလဲ", note: "နောက်ကလိုက်တဲ့အသံအပေါ်မူတည်ပြီး なに သို့မဟုတ် なん လို့ဖတ်ပါတယ်။" }, { kana: "だれ", romaji: "dare", meaning: "ဘယ်သူ" }, { kana: "どこ", romaji: "doko", meaning: "ဘယ်နေရာ / ဘယ်မှာ" }, { kana: "いつ", romaji: "itsu", meaning: "ဘယ်အချိန်" }, { kana: "どう", romaji: "dou", meaning: "ဘယ်လို / ဘယ်လိုလဲ" }, { kana: "どうして", romaji: "doushite", meaning: "ဘာကြောင့်" }, { kana: "どれ", romaji: "dore", meaning: "ဘယ်တစ်ခု" }, { kana: "どの", romaji: "dono", meaning: "ဘယ်...", note: "နောက်မှာ နာမ်တစ်ခုထည့်ပြီး သုံးရပါတယ်။" }, { kana: "いくつ", romaji: "ikutsu", meaning: "ဘယ်နှခု / အသက်ဘယ်လောက်" }, { kana: "いくら", romaji: "ikura", meaning: "ဈေးဘယ်လောက်" },
  ]},
  { label: "Greetings & Expressions", title: "နှုတ်ဆက်စကားနဲ့ နေ့စဉ်အသုံးအနှုန်း", description: "ဂျပန်လူမှုဘဝမှာ နေ့တိုင်းကြားရပြီး အခြေအနေမှန်အလိုက် သုံးရတဲ့ စကားစုများ", words: [
    { kana: "おはようございます", romaji: "ohayou gozaimasu", meaning: "မင်္ဂလာနံနက်ခင်းပါ" }, { kana: "こんにちは", romaji: "konnichiwa", meaning: "မင်္ဂလာနေ့လယ်ခင်းပါ / ဟယ်လို" }, { kana: "こんばんは", romaji: "konbanwa", meaning: "မင်္ဂလာညနေခင်းပါ" }, { kana: "ありがとうございます", romaji: "arigatou gozaimasu", meaning: "ကျေးဇူးအများကြီးတင်ပါတယ်" }, { kana: "すみません", romaji: "sumimasen", meaning: "တောင်းပန်ပါတယ် / ခွင့်ပြုပါ / တစ်ဆိတ်လောက်" }, { kana: "ごめんなさい", romaji: "gomennasai", meaning: "တောင်းပန်ပါတယ်" }, { kana: "はじめまして", romaji: "hajimemashite", meaning: "ပထမဆုံးတွေ့ဆုံခြင်းပါ" }, { kana: "よろしくおねがいします", romaji: "yoroshiku onegaishimasu", meaning: "ကောင်းမွန်စွာ ဆက်ဆံပေးပါ / တွေ့ရတာဝမ်းသာပါတယ်" }, { kana: "いただきます", romaji: "itadakimasu", meaning: "စားသောက်တော့မယ်လို့ ကျေးဇူးတင်စွာပြောခြင်း" }, { kana: "ごちそうさまでした", romaji: "gochisousama deshita", meaning: "စားပြီးနောက် အစားအစာအတွက် ကျေးဇူးတင်စကား" },
  ]},
];
function audioKey(romaji: string) { return romaji.replaceAll(" ", "-").replaceAll("/", "-"); }
function WordCard({ word, number }: { word: Word; number: number }) { return <article className="rounded-[1.5rem] border border-[#ded8ca] bg-[#fffdf8] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black tracking-[.16em] text-[#8a8276]">WORD {String(number).padStart(2, "0")}</p><p lang="ja" className="mt-2 text-3xl font-black text-[#a33a32]">{word.kana}</p><p className="mt-1 text-xs font-bold text-[#746c60]">{word.romaji}</p></div><SoundButton audioUrl={`/audio/n5/vocabulary/adjectives-questions-greetings/${audioKey(word.romaji)}.mp3`} label={word.kana} /></div><MeaningReveal meaning={word.meaning} detail={word.note} /></article>; }
export default function Page() { return <div className="washi-surface min-h-screen bg-[#f7f5ef] text-[#172033]"><header className="border-b border-[#ded8ca] bg-[#fffdf8]"><Container className="py-7"><Link href="/learn/n5/vocabulary" className="text-xs font-bold text-[#746c60]">← Vocabulary Topics</Link><p className="mt-6 text-xs font-black tracking-[.2em] text-[#a33a32] uppercase">Lesson 06 · ことば・あいさつ</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Adjectives, Questions & Greetings</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-[#746c60]">ဖော်ပြချက်၊ မေးခွန်းမေးခြင်းနဲ့ နေ့စဉ်နှုတ်ဆက်ရာမှာ လိုအပ်တဲ့ N5 စကားလုံး ၃၀ ကို အသံနဲ့တွဲပြီး မှတ်မယ်။ Kanji မထည့်သေးပါဘူး။</p></Container></header><Container className="py-10 sm:py-14">{groups.map((group, groupIndex) => <section key={group.label} className={groupIndex ? "mt-14" : ""}><p className="text-xs font-black tracking-[.18em] text-[#a33a32] uppercase">{group.label}</p><h2 className="mt-2 text-2xl font-black">{group.title}</h2><p className="mt-2 text-sm text-[#746c60]">{group.description}</p><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{group.words.map((word, wordIndex) => <WordCard key={word.romaji} word={word} number={groupIndex * 10 + wordIndex + 1} />)}</div></section>)}<div className="mt-12 flex flex-wrap justify-between gap-3"><Link href="/learn/n5/vocabulary/food-places-transport" className="rounded-xl border border-[#cfc6b7] bg-white px-5 py-3 text-sm font-bold">← Previous Lesson</Link><Link href="/learn/n5/grammar" className="rounded-xl bg-[#d43d34] px-5 py-3 text-sm font-black text-white transition hover:bg-[#b92f28]">Grammar စမယ် →</Link></div></Container></div>; }
