import type { Metadata } from "next";
import Link from "next/link";
import { SoundButton } from "@/components/learning/sound-button";
import { Container } from "@/components/ui/container";

export const metadata: Metadata = { title: "Complete Romaji Sounds", description: "အခြေခံမှ ပေါင်းစပ်အသံအထိ Romaji အသံစနစ်အပြည့်ကို Natural Japanese audio ဖြင့်လေ့လာရန်။" };

const basicRows = [
  ["vowels", "Vowels", "a · i · u · e · o", "အ · အိ · အု · အဲ · အို"],
  ["k", "K row", "ka · ki · ku · ke · ko", "က အသံအုပ်စု"], ["s", "S row", "sa · shi · su · se · so", "shi ကို ‘ရှိ’ နဲ့နီးစပ်စွာထွက်ပါ"],
  ["t", "T row", "ta · chi · tsu · te · to", "chi နဲ့ tsu ကို အထူးသတိထားပါ"], ["n", "N row", "na · ni · nu · ne · no", "န အသံအုပ်စု"],
  ["h", "H row", "ha · hi · fu · he · ho", "fu ကို နှုတ်ခမ်းမထိဘဲ ပေါ့ပေါ့ထွက်ပါ"], ["m", "M row", "ma · mi · mu · me · mo", "မ အသံအုပ်စု"],
  ["y", "Y row", "ya · yu · yo", "yi နဲ့ ye မရှိပါ"], ["r", "R row", "ra · ri · ru · re · ro", "r/l ကြားက အသံနဲ့ လျှာဖျားကို တစ်ချက်ထိပါ"],
  ["w", "W & final N", "wa · wo · n", "wo ကို ပုံမှန်စကားမှာ o လို့ထွက်တတ်ပါတယ်"],
];
const voicedRows = [["g", "G row", "ga · gi · gu · ge · go"], ["z", "Z row", "za · ji · zu · ze · zo"], ["d", "D row", "da · ji · zu · de · do"], ["b", "B row", "ba · bi · bu · be · bo"], ["p", "P row", "pa · pi · pu · pe · po"]];
const combinedRows = [["kya", "kya · kyu · kyo"], ["sha", "sha · shu · sho"], ["cha", "cha · chu · cho"], ["nya", "nya · nyu · nyo"], ["hya", "hya · hyu · hyo"], ["mya", "mya · myu · myo"], ["rya", "rya · ryu · ryo"], ["gya", "gya · gyu · gyo"], ["ja", "ja · ju · jo"], ["bya", "bya · byu · byo"], ["pya", "pya · pyu · pyo"]];

function RowCard({ id, title, sounds, note }: { id: string; title: string; sounds: string; note?: string }) {
  return <article className="rounded-2xl border border-[#ded8ca] bg-[#fffdf8] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black text-[#4f7b5e]">{title}</p><p className="mt-3 text-lg font-black tracking-wide text-[#172033]">{sounds}</p></div><SoundButton audioUrl={`/audio/n5/romaji/${id}.mp3`} label={sounds} /></div>{note && <p className="mt-4 border-t border-[#e7e1d4] pt-4 text-xs leading-6 text-[#746c60]">{note}</p>}</article>;
}

export default function RomajiLessonPage() {
  return <div className="washi-surface min-h-screen bg-[#f7f5ef] text-[#172033]"><header className="border-b border-[#ded8ca] bg-[#fffdf8]"><Container className="py-6"><Link href="/learn/n5" className="text-xs font-bold text-[#746c60] hover:text-[#a33a32]">← N5 Course Overview</Link><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black tracking-[0.2em] text-[#a33a32] uppercase">Lesson 01 · Sound Foundation</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Complete Romaji Sounds</h1></div><span className="rounded-full bg-[#e5eee7] px-4 py-2 text-xs font-black text-[#31513e]">30–40 မိနစ်</span></div></Container></header>
  <Container className="py-10 sm:py-14"><section className="grid gap-5 lg:grid-cols-2"><div className="rounded-[1.75rem] border border-[#ded8ca] bg-[#fffdf8] p-6 sm:p-8"><p className="text-xs font-black tracking-[0.18em] text-[#4f7b5e] uppercase">Romaji ဆိုတာဘာလဲ?</p><h2 className="mt-3 text-2xl font-black">ဂျပန်အသံကို Latin alphabet နဲ့ ရေးပြတဲ့စနစ်</h2><p className="mt-4 text-sm leading-8 text-[#625b50]">ဒီသင်ခန်းစာမှာ Japanese စာလုံးမပြသေးဘဲ Romaji စာလုံးနဲ့ native audio ကို တွဲပြီး အသံကို အရင်မှတ်မယ်။ အသံခလုတ်ကို နှိပ်ပြီး အုပ်စုတစ်ခုချင်းစီကို သုံးကြိမ်လိုက်ဆိုပါ။</p></div><div className="rounded-[1.75rem] bg-[#eef4f2] p-6 text-[#193c40] sm:p-8"><p className="text-xs font-black tracking-[0.18em] uppercase">သတိထားရမယ့်အသံ</p><p className="mt-4 text-2xl font-black">shi · chi · tsu · fu · r</p><p className="mt-3 text-sm leading-7">English လိုမဖတ်ဘဲ audio ကို နားထောင်ပြီး ပါးစပ်ပုံစံနဲ့ အသံအတိုအရှည်ကို လိုက်တုပပါ။</p></div></section>
  <section className="pt-12"><p className="text-xs font-black tracking-[0.2em] text-[#a33a32] uppercase">Part 1 · Basic Sounds</p><h2 className="mt-3 text-3xl font-black">အခြေခံအသံအုပ်စုများ</h2><div className="mt-7 grid gap-4 sm:grid-cols-2">{basicRows.map(([id,title,sounds,note]) => <RowCard key={id} id={id} title={title} sounds={sounds} note={note} />)}</div></section>
  <section className="pt-12"><p className="text-xs font-black tracking-[0.2em] text-[#a33a32] uppercase">Part 2 · Voiced Sounds</p><h2 className="mt-3 text-3xl font-black">အသံပြင်းအုပ်စုများ</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{voicedRows.map(([id,title,sounds]) => <RowCard key={id} id={id} title={title} sounds={sounds} />)}</div><p className="mt-4 rounded-xl bg-[#fff8e7] p-4 text-xs leading-6 text-[#765716]">မှတ်ချက် — Modern standard pronunciation မှာ D row ရဲ့ အလယ်အသံနှစ်ခုကိုလည်း <strong>ji</strong> နဲ့ <strong>zu</strong> လို့ အသံထွက်ပါတယ်။</p></section>
  <section className="pt-12"><p className="text-xs font-black tracking-[0.2em] text-[#a33a32] uppercase">Part 3 · Combined Sounds</p><h2 className="mt-3 text-3xl font-black">ပေါင်းစပ်အသံများ</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{combinedRows.map(([id,sounds]) => <RowCard key={id} id={id} title="Combined" sounds={sounds} />)}</div></section>
  <section className="pt-12"><p className="text-xs font-black tracking-[0.2em] text-[#a33a32] uppercase">Part 4 · Special Rules</p><h2 className="mt-3 text-3xl font-black">အထူးအသံထွက်စည်းမျဉ်းများ</h2><div className="mt-7 grid gap-4 lg:grid-cols-3"><RowCard id="double" title="Double consonant" sounds="kitte · gakkou" note="ဗျည်းနှစ်ထပ်မတိုင်ခင် အသံကို ခဏရပ်ပါ။" /><RowCard id="long" title="Long vowel" sounds="Toukyou · okaasan" note="သရအသံရှည်ကို ပုံမှန်အသံထက် နှစ်ဆနီးပါးဆွဲပါ။" /><RowCard id="final-n" title="Final n" sounds="hon · Nihon" note="စကားလုံးအဆုံးက n အသံကို သီးခြားတစ်ချက်ထွက်ပါ။" /></div></section>
  <div className="mt-10 grid gap-5 lg:grid-cols-[1fr_22rem]"><section className="rounded-[1.75rem] border border-[#d8c8aa] bg-[#fff8e7] p-6 sm:p-8"><p className="text-xs font-black tracking-[0.18em] text-[#9a6721] uppercase">လေ့ကျင့်နည်း</p><ol className="mt-5 space-y-3 text-sm leading-7 text-[#625b50]"><li>1. Row တစ်ခုရဲ့ audio ကို အရင်နားထောင်ပါ။</li><li>2. Romaji ကိုကြည့်ပြီး အသံနောက်က လိုက်ဆိုပါ။</li><li>3. မကြည့်ဘဲ ထပ်ဆိုပြီး အသံကို မှတ်မိအောင်လုပ်ပါ။</li></ol></section><section className="rounded-[1.75rem] bg-[#111827] p-6 text-white sm:p-8"><p className="text-xs font-black tracking-[0.18em] text-[#f2d48f] uppercase">Quick Practice</p><h2 className="mt-3 text-2xl font-black">Romaji Quiz</h2><p className="mt-3 text-sm leading-7 text-white/55">အသံနားထောင်ပြီး ဖြေရမယ့် မေးခွန်း ၅ ခုပါ။ ၃ မိနစ်ခန့်ပဲ ကြာပါမယ်။</p><Link href="/learn/n5/romaji/quiz" className="mt-6 inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-[#c83f35] px-5 py-3 text-sm font-black text-white transition hover:bg-[#a92f28]">Quiz Practice စမယ် →</Link></section></div>
  <div className="mt-8 flex justify-between gap-3"><Link href="/learn/n5" className="rounded-xl border border-[#cfc6b7] bg-[#fffdf8] px-5 py-3 text-sm font-bold text-[#514b41]">← Course Overview</Link><span className="rounded-xl bg-[#d7d1c5] px-5 py-3 text-sm font-bold text-[#7c7468]">နောက်သင်ခန်းစာ · မကြာမီ</span></div></Container></div>;
}
