import type {Metadata} from "next";import Link from "next/link";import {Container} from "@/components/ui/container";import {HiraganaSoundGrid,type SoundGroup} from "@/components/learning/hiragana-sound-grid";
export const metadata:Metadata={title:"Katakana Voiced Sounds"};
const groups:SoundGroup[]=[
 {title:"ガ行 · G အသံ",subtitle:"カ行 ကို ゛ထည့်ထားတဲ့အသံ",items:[["ガ","ga"],["ギ","gi"],["グ","gu"],["ゲ","ge"],["ゴ","go"]].map(([kana,romaji])=>({kana,romaji}))},
 {title:"ザ行 · Z အသံ",subtitle:"サ行 ကို ゛ထည့်ထားတဲ့အသံ",items:[{kana:"ザ",romaji:"za"},{kana:"ジ",romaji:"ji",note:"ji လို့ဖတ်ပါတယ်"},{kana:"ズ",romaji:"zu"},{kana:"ゼ",romaji:"ze"},{kana:"ゾ",romaji:"zo"}]},
 {title:"ダ行 · D အသံ",subtitle:"タ行 ကို ゛ထည့်ထားတဲ့အသံ",items:[{kana:"ダ",romaji:"da"},{kana:"ヂ",romaji:"ji",audioKey:"ji-d"},{kana:"ヅ",romaji:"zu",audioKey:"zu-d"},{kana:"デ",romaji:"de"},{kana:"ド",romaji:"do"}]},
 {title:"バ行 · B အသံ",subtitle:"ハ行 ကို ゛ထည့်ထားတဲ့အသံ",items:[["バ","ba"],["ビ","bi"],["ブ","bu"],["ベ","be"],["ボ","bo"]].map(([kana,romaji])=>({kana,romaji}))},
 {title:"パ行 · P အသံ",subtitle:"ハ行 ကို ゜ထည့်ထားတဲ့အသံ",items:[["パ","pa"],["ピ","pi"],["プ","pu"],["ペ","pe"],["ポ","po"]].map(([kana,romaji])=>({kana,romaji}))},
];
export default function Page(){return <div className="washi-surface min-h-screen bg-[#f7f5ef] text-[#172033]"><header className="border-b border-[#ded8ca] bg-[#fffdf8]"><Container className="py-7"><Link href="/learn/n5" className="text-xs font-bold text-[#746c60]">← N5 Course Overview</Link><p className="mt-6 text-xs font-black tracking-[.2em] text-[#a33a32] uppercase">Sound Recognition · 濁音・半濁音</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">အသံပြောင်း Katakana</h1><p className="mt-3 text-sm text-[#746c60]">ရေးနည်းမပါဘဲ ゛နဲ့ ゜ ကြောင့် ပြောင်းသွားတဲ့အသံကို နားထောင်မှတ်သားပါ။</p></Container></header><Container className="py-10 sm:py-14"><HiraganaSoundGrid groups={groups} audioBasePath="/audio/n5/katakana/variants"/><div className="mt-10 flex justify-between gap-3"><Link href="/learn/n5/katakana/w-row" className="rounded-xl border border-[#cfc6b7] bg-white px-5 py-3 text-sm font-bold">← Previous Lesson</Link><Link href="/learn/n5/katakana/combined-sounds" className="rounded-xl bg-[#c83f35] px-5 py-3 text-sm font-black text-white">Next Lesson →</Link></div></Container></div>;}
