import type { Metadata } from "next";
import Link from "next/link";
import { MeaningReveal } from "@/components/learning/meaning-reveal";
import { SoundButton } from "@/components/learning/sound-button";
import { Container } from "@/components/ui/container";

export const metadata: Metadata = { title: "N5 Daily Life Vocabulary" };
type Word = { kana: string; romaji: string; meaning: string; note?: string };
const groups: { label: string; title: string; description: string; words: Word[] }[] = [
  { label: "People & Family", title: "လူနဲ့ မိသားစု", description: "ကိုယ့်အကြောင်းနဲ့ မိသားစုဝင်တွေကို ပြောတဲ့အခါ အသုံးများတဲ့ စကားလုံးများ", words: [
    { kana: "わたし", romaji: "watashi", meaning: "ကျွန်တော် / ကျွန်မ" }, { kana: "あなた", romaji: "anata", meaning: "သင် / မင်း", note: "တစ်ဖက်လူရဲ့ နာမည်သိရင် နာမည်ကို သုံးတာ ပိုသဘာဝကျပါတယ်။" }, { kana: "かぞく", romaji: "kazoku", meaning: "မိသားစု" }, { kana: "ちち", romaji: "chichi", meaning: "ကိုယ့်အဖေ" }, { kana: "はは", romaji: "haha", meaning: "ကိုယ့်အမေ" }, { kana: "あに", romaji: "ani", meaning: "ကိုယ့်အစ်ကို" }, { kana: "あね", romaji: "ane", meaning: "ကိုယ့်အစ်မ" }, { kana: "おとうと", romaji: "otouto", meaning: "ညီလေး" }, { kana: "いもうと", romaji: "imouto", meaning: "ညီမလေး" }, { kana: "ともだち", romaji: "tomodachi", meaning: "သူငယ်ချင်း" },
  ]},
  { label: "Home & Everyday Things", title: "အိမ်နဲ့ နေ့စဉ်သုံးပစ္စည်း", description: "အိမ်မှာနဲ့ နေ့စဉ်ဘဝထဲ မကြာခဏတွေ့ရတဲ့ အရာများ", words: [
    { kana: "いえ", romaji: "ie", meaning: "အိမ်" }, { kana: "へや", romaji: "heya", meaning: "အခန်း" }, { kana: "つくえ", romaji: "tsukue", meaning: "စားပွဲ" }, { kana: "いす", romaji: "isu", meaning: "ကုလားထိုင်" }, { kana: "ほん", romaji: "hon", meaning: "စာအုပ်" }, { kana: "みず", romaji: "mizu", meaning: "ရေ" }, { kana: "ごはん", romaji: "gohan", meaning: "ထမင်း / အစားအစာ" }, { kana: "くるま", romaji: "kuruma", meaning: "ကား" }, { kana: "でんわ", romaji: "denwa", meaning: "တယ်လီဖုန်း" }, { kana: "かばん", romaji: "kaban", meaning: "အိတ်" },
  ]},
  { label: "Daily Actions", title: "နေ့စဉ်လုပ်ဆောင်ချက်", description: "နေ့တိုင်း ပြောဆိုရာမှာ မရှိမဖြစ်သုံးရတဲ့ အခြေခံကြိယာများ", words: [
    { kana: "おきる", romaji: "okiru", meaning: "အိပ်ရာထသည်" }, { kana: "ねる", romaji: "neru", meaning: "အိပ်သည်" }, { kana: "たべる", romaji: "taberu", meaning: "စားသည်" }, { kana: "のむ", romaji: "nomu", meaning: "သောက်သည်" }, { kana: "いく", romaji: "iku", meaning: "သွားသည်" }, { kana: "くる", romaji: "kuru", meaning: "လာသည်" }, { kana: "みる", romaji: "miru", meaning: "ကြည့်သည်" }, { kana: "きく", romaji: "kiku", meaning: "နားထောင်သည် / မေးသည်" }, { kana: "はなす", romaji: "hanasu", meaning: "စကားပြောသည်" }, { kana: "よむ", romaji: "yomu", meaning: "ဖတ်သည်" },
  ]},
];
function WordCard({ word, number }: { word: Word; number: number }) { return <article className="rounded-[1.5rem] border border-[#ded8ca] bg-[#fffdf8] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black tracking-[.16em] text-[#8a8276]">WORD {String(number).padStart(2, "0")}</p><p lang="ja" className="mt-2 text-3xl font-black text-[#a33a32]">{word.kana}</p><p className="mt-1 text-xs font-bold text-[#746c60]">{word.romaji}</p></div><SoundButton audioUrl={`/audio/n5/vocabulary/daily-life/${word.romaji}.mp3`} label={word.kana} /></div><MeaningReveal meaning={word.meaning} detail={word.note} /></article>; }
export default function Page() { return <div className="washi-surface min-h-screen bg-[#f7f5ef] text-[#172033]"><header className="border-b border-[#ded8ca] bg-[#fffdf8]"><Container className="py-7"><Link href="/learn/n5/vocabulary" className="text-xs font-bold text-[#746c60]">← Vocabulary Topics</Link><p className="mt-6 text-xs font-black tracking-[.2em] text-[#a33a32] uppercase">Lesson 04 · まいにち</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Daily Life Vocabulary</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-[#746c60]">N5 မှာ အများဆုံးတွေ့ရတဲ့ နေ့စဉ်သုံးစကားလုံး ၃၀ ကို Hiragana၊ Romaji နဲ့ အသံတွဲပြီး မှတ်မယ်။ မြန်မာအဓိပ္ပာယ်ကို ကိုယ်တိုင်စဉ်းစားပြီးမှ ဖွင့်ကြည့်ပါ။</p></Container></header><Container className="py-10 sm:py-14">{groups.map((group, groupIndex) => <section key={group.label} className={groupIndex ? "mt-14" : ""}><p className="text-xs font-black tracking-[.18em] text-[#a33a32] uppercase">{group.label}</p><h2 className="mt-2 text-2xl font-black">{group.title}</h2><p className="mt-2 text-sm text-[#746c60]">{group.description}</p><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{group.words.map((word, wordIndex) => <WordCard key={word.romaji} word={word} number={groupIndex * 10 + wordIndex + 1} />)}</div></section>)}<div className="mt-12 flex flex-wrap justify-between gap-3"><Link href="/learn/n5/vocabulary/days-dates-months" className="rounded-xl border border-[#cfc6b7] bg-white px-5 py-3 text-sm font-bold">← Previous Lesson</Link><Link href="/learn/n5/vocabulary" className="rounded-xl bg-[#315f63] px-5 py-3 text-sm font-black text-white transition hover:bg-[#244a4d]">Vocabulary Topics →</Link></div></Container></div>; }
