import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { KanjiStrokeDiagram } from "@/components/learning/kanji-stroke-diagram";
import { KanjiTracingSection } from "@/components/learning/kanji-tracing-section";
import { MeaningReveal } from "@/components/learning/meaning-reveal";
import { SoundButton } from "@/components/learning/sound-button";
import { Container } from "@/components/ui/container";
import { getRemainingN5KanjiLesson,kanjiAssetName,remainingN5KanjiLessons } from "@/data/n5-kanji-course";

export function generateStaticParams(){return remainingN5KanjiLessons.map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const lesson=getRemainingN5KanjiLesson((await params).slug);return {title:lesson?`${lesson.title} | N5 Kanji`:"N5 Kanji"};}

export default async function Page({params}:{params:Promise<{slug:string}>}){
 const lesson=getRemainingN5KanjiLesson((await params).slug); if(!lesson) notFound();
 const index=remainingN5KanjiLessons.findIndex(({slug})=>slug===lesson.slug); const next=remainingN5KanjiLessons[index+1];
 return <div className="washi-surface min-h-screen bg-[#f7f5ef] text-[#172033]"><header className="border-b border-[#ded8ca] bg-[#fffdf8]"><Container className="py-8 sm:py-10"><Link href="/learn/n5/kanji" className="text-xs font-bold text-[#746c60]">← Kanji Lessons</Link><p className="mt-6 text-xs font-black tracking-[.2em] text-[#a33a32] uppercase">Lesson {lesson.no} · N5 Core Kanji</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">{lesson.title}</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-[#746c60]">{lesson.subtitle}။ Kanji တစ်လုံးစီကို ပုံမှတ်နည်း၊ ဆွဲချက်အစဉ်၊ ဖတ်ပုံနဲ့ အသုံးဝင်စကားလုံးတွဲပြီး လေ့လာပါ။</p></Container></header><Container className="py-10 sm:py-14">
 <div className="space-y-8">{lesson.kanji.map((item,i)=><article key={item.char} className="overflow-hidden rounded-[2rem] border border-[#ded8ca] bg-[#fffdf8]"><div className="grid lg:grid-cols-[18rem_1fr]"><div className="border-b border-[#ded8ca] bg-[#f2eee5] p-6 lg:border-b-0 lg:border-r"><div className="flex items-center justify-between"><span className="text-[10px] font-black tracking-[.16em] text-[#746c60]">KANJI {String(i+1).padStart(2,"0")}</span><span className="text-4xl" role="img" aria-label={item.meaning}>{item.icon}</span></div><div className="mt-5"><KanjiStrokeDiagram character={item.char} asset={`/strokes/kanji/${kanjiAssetName(item.char)}.svg`} strokes={item.strokes}/></div></div><div className="p-6 sm:p-8"><div className="flex items-start justify-between gap-5"><div><p lang="ja" className="text-7xl font-black text-[#a33a32]">{item.char}</p><p className="mt-2 text-lg font-black">{item.meaning}</p></div><SoundButton audioUrl={`/audio/n5/kanji/core/${item.audioKey}.mp3`} label={item.word}/></div><div className="mt-6 rounded-2xl border border-[#e3c99b] bg-[#fff8e7] p-5"><p className="text-xs font-black tracking-[.15em] text-[#9a6721] uppercase">🧠 ပုံနဲ့မှတ်နည်း</p><p className="mt-3 text-sm font-bold leading-7 text-[#625b50]">{item.mnemonic}</p></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-[#f2eee5] p-4"><p className="text-[10px] font-black text-[#746c60] uppercase">On-reading</p><p lang="ja" className="mt-2 text-lg font-black">{item.on}</p></div><div className="rounded-xl bg-[#e8efe9] p-4"><p className="text-[10px] font-black text-[#31513e] uppercase">Kun-reading</p><p lang="ja" className="mt-2 text-lg font-black">{item.kun}</p></div></div><div className="mt-5 rounded-xl border border-[#ded8ca] p-4"><p className="text-[10px] font-black text-[#746c60] uppercase">ပထမဆုံး မှတ်ရမယ့်စကားလုံး</p><p lang="ja" className="mt-2 text-xl font-black text-[#a33a32]">{item.word}</p><MeaningReveal meaning={item.wordMeaning}/></div></div></div></article>)}</div>
 <div className="mt-12"><KanjiTracingSection characters={lesson.kanji.map(({char})=>char)}/></div><div className="mt-10 flex flex-wrap justify-between gap-3"><Link href={index===0?"/learn/n5/kanji/numbers-one-five":`/learn/n5/kanji/lesson/${remainingN5KanjiLessons[index-1].slug}`} className="rounded-xl border border-[#cfc6b7] bg-white px-5 py-3 text-sm font-bold">← Previous Lesson</Link>{next?<Link href={`/learn/n5/kanji/lesson/${next.slug}`} className="rounded-xl bg-[#d43d34] px-5 py-3 text-sm font-black text-white">Next Lesson →</Link>:<Link href="/learn/n5/kanji/quiz" className="rounded-xl bg-[#315f63] px-5 py-3 text-sm font-black text-white">✓ Kanji Quiz ဖြေမယ် →</Link>}</div><p className="mt-8 text-center text-[10px] text-[#9a9185]">Stroke diagrams: KanjiVG · CC BY-SA 3.0</p>
 </Container></div>;
}
