import type {Metadata} from "next";import Link from "next/link";import {Container} from "@/components/ui/container";
export const metadata:Metadata={title:"N5 Vocabulary"};
const topics=[
 {no:"01",jp:"かず",title:"Numbers 1–10",detail:"အခြေခံနံပါတ် ၁ ကနေ ၁၀ အထိ Hiragana၊ Romaji၊ မြန်မာအဓိပ္ပာယ်နဲ့ အသံ",count:"10 words",href:"/learn/n5/vocabulary/numbers-1-10",active:true},
 {no:"02",jp:"じかん",title:"Time & Hours",detail:"၁ နာရီကနေ ၁၂ နာရီ၊ နံနက်/ညနေ၊ နာရီဝက်နဲ့ အချိန်မေးမြန်းပုံ",count:"18 words",href:"/learn/n5/vocabulary/time-hours",active:true},
 {no:"03",jp:"カレンダー",title:"Days, Dates & Months",detail:"တစ်ပတ်ခုနစ်ရက်၊ ၁၂ လနဲ့ ရက်စွဲ ၁ ရက်ကနေ ၃၁ ရက်အထိ",count:"50 words",href:"/learn/n5/vocabulary/days-dates-months",active:true},
 {no:"04",jp:"まいにち",title:"Daily Life",detail:"လူနဲ့ မိသားစု၊ အိမ်သုံးပစ္စည်းနဲ့ နေ့စဉ်လုပ်ဆောင်ချက်များ",count:"30 words",href:"/learn/n5/vocabulary/daily-life",active:true},
];
export default function Page(){return <div className="washi-surface min-h-screen bg-[#f7f5ef] text-[#172033]"><header className="bg-[#111827] text-white"><Container className="py-12 sm:py-16"><Link href="/learn/n5" className="text-xs font-bold text-white/55 hover:text-white">← N5 Course Overview</Link><p className="mt-8 text-xs font-black tracking-[.2em] text-[#9fd0ac] uppercase">Module 04 · 語彙</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">N5 Vocabulary</h1><p className="mt-4 max-w-2xl text-sm leading-8 text-white/65">နေ့စဉ်သုံးအကြောင်းအရာအလိုက် Japanese စကားလုံးတွေကို စာလုံး၊ ဖတ်ပုံ၊ မြန်မာအဓိပ္ပာယ်နဲ့ အသံတွဲပြီး လေ့လာမယ်။</p></Container></header><Container className="py-10 sm:py-14"><p className="text-xs font-black tracking-[.2em] text-[#a33a32] uppercase">N5 Essential Vocabulary</p><h2 className="mt-3 text-3xl font-black">Vocabulary Topics</h2><div className="mt-7 grid gap-5 md:grid-cols-2">{topics.map((topic)=>{const card=<article className={`h-full rounded-[1.75rem] border border-[#ded8ca] bg-[#fffdf8] p-6 ${topic.active?"transition hover:-translate-y-1 hover:border-[#4f7b5e] hover:shadow-lg":"opacity-55"}`}><span className={`flex size-12 items-center justify-center rounded-full text-xs font-black ${topic.active?"bg-[#4f7b5e] text-white":"bg-[#eee9df] text-[#8a8276]"}`}>{topic.no}</span><p lang="ja" className="mt-5 text-xs font-bold text-[#a33a32]">{topic.jp}</p><h3 className="mt-1 text-xl font-black">{topic.title}</h3><p className="mt-3 text-sm leading-7 text-[#746c60]">{topic.detail}</p><p className="mt-5 text-xs font-black text-[#31513e]">{topic.count}{topic.active?" →":""}</p></article>;return topic.href?<Link key={topic.no} href={topic.href}>{card}</Link>:<div key={topic.no}>{card}</div>;})}</div></Container></div>;}
