"use client";

import { useRef, useState } from "react";
import type { N5KanjiQuizItem } from "@/data/n5-kanji-course";

type Mode="picture"|"listening"|"meaning";
type Answer={item:N5KanjiQuizItem;selected:string;correct:boolean};
const modeInfo:Record<Mode,{number:string;icon:string;title:string;detail:string}>={
 picture:{number:"01",icon:"🖼️",title:"ပုံကြည့်ပြီး Kanji ရွေးမယ်",detail:"မှတ်နည်းပုံရိပ်ကိုကြည့်ပြီး ကိုက်ညီတဲ့ Kanji ကို ရွေးပါ။"},
 listening:{number:"02",icon:"🔊",title:"အသံနားထောင်ပြီး Kanji ရွေးမယ်",detail:"Japanese စကားလုံးအသံကို နားထောင်ပြီး ပါဝင်တဲ့ Kanji ကို ရွေးပါ။"},
 meaning:{number:"03",icon:"文",title:"Kanji ကြည့်ပြီး အဓိပ္ပာယ်ရွေးမယ်",detail:"Kanji ကိုကြည့်ပြီး မှန်ကန်တဲ့ မြန်မာအဓိပ္ပာယ်ကို ရွေးပါ။"},
};
function shuffled<T>(values:T[]){return [...values].sort(()=>Math.random()-.5);}

export function KanjiQuizSession({items}:{items:N5KanjiQuizItem[]}){
 const [mode,setMode]=useState<Mode|null>(null); const [questions,setQuestions]=useState<N5KanjiQuizItem[]>([]); const [index,setIndex]=useState(0); const [selected,setSelected]=useState<string|null>(null); const [answers,setAnswers]=useState<Answer[]>([]); const audioRef=useRef<HTMLAudioElement>(null);
 const current=questions[index]; const finished=mode&&questions.length>0&&index>=questions.length;
 function optionsFor(item:N5KanjiQuizItem){const answer=mode==="meaning"?item.meaning:item.char;const pool=items.map((candidate)=>mode==="meaning"?candidate.meaning:candidate.char).filter((value,pos,all)=>value!==answer&&all.indexOf(value)===pos);return shuffled([answer,...shuffled(pool).slice(0,3)]);}
 const [cachedOptions,setCachedOptions]=useState<string[]>([]);
 function begin(nextMode:Mode){const sample=shuffled(items).slice(0,10);setMode(nextMode);setQuestions(sample);setIndex(0);setSelected(null);setAnswers([]);const answer=nextMode==="meaning"?sample[0].meaning:sample[0].char;const pool=items.map((x)=>nextMode==="meaning"?x.meaning:x.char).filter((x,p,a)=>x!==answer&&a.indexOf(x)===p);setCachedOptions(shuffled([answer,...shuffled(pool).slice(0,3)]));}
 function choose(value:string){if(selected||!current||!mode)return;const answer=mode==="meaning"?current.meaning:current.char;setSelected(value);setAnswers((old)=>[...old,{item:current,selected:value,correct:value===answer}]);}
 function next(){const nextIndex=index+1;setIndex(nextIndex);setSelected(null);if(nextIndex<questions.length&&mode)setCachedOptions(optionsFor(questions[nextIndex]));}
 if(!mode)return <div><div className="grid gap-5 lg:grid-cols-3">{(Object.keys(modeInfo) as Mode[]).map((key)=>{const info=modeInfo[key];return <button key={key} type="button" onClick={()=>begin(key)} className="group rounded-[1.75rem] border border-[#ded8ca] bg-[#fffdf8] p-6 text-left transition hover:-translate-y-1 hover:border-[#4f7b5e] hover:shadow-lg"><div className="flex items-center justify-between"><span className="flex size-11 items-center justify-center rounded-full bg-[#4f7b5e] text-xs font-black text-white">{info.number}</span><span className="text-4xl">{info.icon}</span></div><h2 className="mt-6 text-xl font-black">{info.title}</h2><p className="mt-3 text-sm leading-7 text-[#746c60]">{info.detail}</p><p className="mt-6 text-xs font-black text-[#31513e]">မေးခွန်း ၁၀ ခု စမယ် →</p></button>})}</div><p className="mt-6 text-center text-xs text-[#8a8276]">Quiz စတိုင်း Kanji ၈၀ ထဲက မေးခွန်းအသစ် ၁၀ ခု ရွေးပေးပါမယ်။</p></div>;
 if(finished){const score=answers.filter(({correct})=>correct).length;const wrong=answers.filter(({correct})=>!correct);return <section className="rounded-[2rem] border border-[#ded8ca] bg-[#fffdf8] p-6 sm:p-10"><div className="text-center"><p className="text-xs font-black tracking-[.18em] text-[#a33a32] uppercase">Quiz Complete</p><p className="mt-4 text-6xl font-black text-[#31513e]">{score}<span className="text-2xl text-[#8a8276]"> / 10</span></p><h2 className="mt-4 text-2xl font-black">{score>=8?"ကောင်းပါတယ်!":"ထပ်လေ့ကျင့်ရအောင်"}</h2></div>{wrong.length>0&&<div className="mt-8"><p className="text-sm font-black">ပြန်ကြည့်ရမယ့် Kanji</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{wrong.map(({item,selected},i)=><div key={`${item.char}-${i}`} className="flex items-center gap-4 rounded-xl bg-[#fff3f0] p-4"><span lang="ja" className="text-3xl font-black text-[#a33a32]">{item.char}</span><div><p className="text-sm font-black">{item.meaning}</p><p className="mt-1 text-[11px] text-[#8a8276]">သင်ရွေးခဲ့တာ · {selected}</p></div></div>)}</div></div>}<div className="mt-8 flex flex-wrap justify-center gap-3"><button type="button" onClick={()=>begin(mode)} className="rounded-xl bg-[#d43d34] px-5 py-3 text-sm font-black text-white">ဒီ Mode ပြန်ဖြေမယ်</button><button type="button" onClick={()=>{setMode(null);setQuestions([]);setAnswers([]);}} className="rounded-xl border border-[#cfc6b7] px-5 py-3 text-sm font-black">အခြား Mode ရွေးမယ်</button></div></section>}
 const info=modeInfo[mode]; const answer=mode==="meaning"?current.meaning:current.char;
 return <section className="overflow-hidden rounded-[2rem] border border-[#ded8ca] bg-[#fffdf8]"><div className="border-b border-[#ded8ca] bg-[#f2eee5] px-6 py-5"><div className="flex items-center justify-between gap-4"><div><p className="text-[10px] font-black tracking-[.16em] text-[#a33a32] uppercase">{info.title}</p><p className="mt-1 text-sm font-bold text-[#746c60]">မေးခွန်း {index+1} / 10</p></div><button type="button" onClick={()=>{setMode(null);setQuestions([]);}} className="text-xs font-black text-[#746c60]">Mode ပြောင်းမယ်</button></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#ded8ca]"><div className="h-full rounded-full bg-[#4f7b5e] transition-all" style={{width:`${(index+1)*10}%`}}/></div></div>
 <div className="p-6 sm:p-10"><div className="flex min-h-44 flex-col items-center justify-center rounded-[1.5rem] border border-[#e3c99b] bg-[#fff8e7] p-6 text-center">{mode==="picture"&&<><span className="text-7xl" role="img" aria-label="မှတ်နည်းပုံ">{current.icon}</span><p className="mt-4 text-sm font-black text-[#746c60]">ဒီပုံနဲ့ ဆက်စပ်တဲ့ Kanji က ဘာလဲ?</p></>}{mode==="listening"&&<><audio ref={audioRef} src={current.audioUrl}/><button type="button" onClick={()=>{if(audioRef.current){audioRef.current.currentTime=0;void audioRef.current.play();}}} className="flex size-20 items-center justify-center rounded-full bg-[#315f63] text-3xl text-white shadow-lg" aria-label="အသံဖွင့်မယ်">▶</button><p className="mt-4 text-sm font-black text-[#746c60]">အသံကို လိုအပ်သလောက် ပြန်နားထောင်နိုင်ပါတယ်</p></>}{mode==="meaning"&&<><span lang="ja" className="text-8xl font-black text-[#a33a32]">{current.char}</span><p className="mt-4 text-sm font-black text-[#746c60]">ဒီ Kanji ရဲ့ အဓိပ္ပာယ်က ဘာလဲ?</p></>}</div>
 <div className="mt-6 grid gap-3 sm:grid-cols-2">{cachedOptions.map((option)=>{const isAnswer=option===answer;const state=selected?(isAnswer?"border-[#4f7b5e] bg-[#e5eee7] text-[#31513e]":option===selected?"border-[#d43d34] bg-[#fff0ed] text-[#a33a32]":"border-[#ded8ca] bg-white text-[#8a8276]"):"border-[#ded8ca] bg-white hover:border-[#4f7b5e]";return <button key={option} type="button" disabled={!!selected} onClick={()=>choose(option)} className={`min-h-16 rounded-xl border px-5 py-4 text-center text-lg font-black transition ${state}`}><span lang={mode==="meaning"?undefined:"ja"}>{option}</span></button>})}</div>
 {selected&&<div className={`mt-6 rounded-xl p-5 ${selected===answer?"bg-[#e5eee7] text-[#31513e]":"bg-[#fff0ed] text-[#a33a32]"}`}><p className="font-black">{selected===answer?"✓ မှန်ပါတယ်":"✕ မမှန်သေးပါ"}</p><p className="mt-2 text-sm">အဖြေမှန် · <span lang="ja" className="font-black">{current.char}</span> — {current.meaning}</p><button type="button" onClick={next} className="mt-4 rounded-lg bg-[#111827] px-4 py-2.5 text-xs font-black text-white">{index===9?"ရလဒ်ကြည့်မယ်":"နောက်မေးခွန်း →"}</button></div>}</div></section>;
}
