"use client";
import { useState } from "react";

const items = [
  { sign: "営業時間\n午前九時〜午後六時\n火曜日 休み", question: "ဒီဆိုင်က ဘယ်နေ့ပိတ်ပါသလဲ။", options: ["တနင်္လာ", "အင်္ဂါ", "ဗုဒ္ဓဟူး"], answer: 1, explanation: "火曜日 = အင်္ဂါနေ့၊ 休み = ပိတ်ရက်။ 営業時間 က ဖွင့်ချိန်ကိုဆိုလိုပါတယ်။" },
  { sign: "ここで しゃしんを\nとらないでください", question: "ဒီနေရာမှာ ဘာမလုပ်ရပါသလဲ။", options: ["စကားမပြောရ", "ဓာတ်ပုံမရိုက်ရ", "မစားရ"], answer: 1, explanation: "しゃしん = ဓာတ်ပုံ၊ とらないでください = မရိုက်ပါနဲ့။ ないでください က တားမြစ်/မလုပ်ဖို့ တောင်းဆိုတဲ့ပုံစံပါ။" },
  { sign: "エレベーターは\nみぎです →", question: "Elevator က ဘယ်ဘက်မှာရှိပါသလဲ။", options: ["ညာဘက်", "ဘယ်ဘက်", "အပေါ်ထပ်"], answer: 0, explanation: "みぎ = ညာဘက်။ မြှား → နဲ့စာသားနှစ်ခုလုံးက ညာဘက်ကိုညွှန်ထားပါတယ်။" },
];
export function SignReadingPractice(){const [i,setI]=useState(0);const [pick,setPick]=useState<number|null>(null);const [score,setScore]=useState(0);const [done,setDone]=useState(false);const q=items[i];function choose(n:number){if(pick!==null)return;setPick(n);if(n===q.answer)setScore(v=>v+1)}function next(){if(i===2)setDone(true);else{setI(v=>v+1);setPick(null)}}function reset(){setI(0);setPick(null);setScore(0);setDone(false)}if(done)return <div className="rounded-[1.75rem] bg-[#111827] p-8 text-center text-white"><p className="text-xs font-black tracking-[.18em] text-[#9fd0ac] uppercase">Signs Complete</p><p className="mt-4 text-4xl font-black">{score} / 3</p><p className="mt-3 text-sm text-white/60">အချိန်၊ စည်းကမ်းနဲ့ နေရာညွှန်ကို ဖတ်နိုင်မှုရလဒ်ပါ။</p><button onClick={reset} className="mt-6 rounded-xl bg-[#c83f35] px-5 py-3 text-sm font-black">ပြန်လေ့ကျင့်မယ်</button></div>;return <div className="rounded-[1.75rem] border border-[#d8c8aa] bg-[#fffdf8] p-5 sm:p-8"><div className="flex justify-between text-xs font-black"><span className="tracking-[.16em] text-[#a33a32]">SIGN {i+1} / 3</span><span className="text-[#746c60]">Score {score}</span></div><p lang="ja" className="mt-5 whitespace-pre-line rounded-2xl border-2 border-[#172033] bg-white p-6 text-center text-xl font-black leading-9">{q.sign}</p><h3 className="mt-6 text-lg font-black">{q.question}</h3><div className="mt-4 grid gap-3">{q.options.map((o,n)=><button key={o} disabled={pick!==null} onClick={()=>choose(n)} className={`min-h-12 rounded-xl border px-4 py-3 text-left text-sm font-bold ${pick!==null&&n===q.answer?"border-[#47745a] bg-[#e4f0e7] text-[#254632]":pick===n?"border-[#c83f35] bg-[#fbe5e2] text-[#8d2922]":"border-[#d8d1c4] bg-white hover:border-[#a33a32]"}`}>{n+1}. {o}</button>)}</div>{pick!==null&&<div className="mt-5 rounded-2xl bg-[#f2eee5] p-5"><p className="font-black">{pick===q.answer?"မှန်ပါတယ် ✓":"မမှန်သေးပါ"}</p><p className="mt-2 text-sm leading-7 text-[#625b50]">{q.explanation}</p><button onClick={next} className="mt-4 rounded-xl bg-[#111827] px-5 py-3 text-sm font-black text-white">{i===2?"ရလဒ်ကြည့်မယ်":"နောက်မေးခွန်း →"}</button></div>}</div>}
